import {
  FiTruck,
  FiShield,
  FiRefreshCcw,
  FiCreditCard,
  FiGift,
  FiHeadphones,
  FiPackage,
  FiLock,
  FiStar,
  FiHeart,
  FiCheckCircle,
  FiAward,
  FiClock,
  FiTag,
  FiThumbsUp,
  FiGlobe,
  FiShoppingCart,
  FiMapPin,
  FiBell,
  FiMessageCircle,
  FiMail,
  FiPhone,
  FiUsers,
  FiBookmark,
  FiBox,
  FiBriefcase,
  FiCamera,
  FiCoffee,
  FiCompass,
  FiFeather,
  FiFlag,
  FiHome,
  FiImage,
  FiLayers,
  FiLifeBuoy,
  FiMonitor,
  FiMoon,
  FiNavigation,
  FiPaperclip,
  FiSend,
  FiSettings,
  FiShoppingBag,
  FiSun,
  FiTarget,
  FiTool,
  FiUnlock,
  FiUserCheck,
  FiWifi,
  FiZap,
} from "react-icons/fi";

import { LiaHandshakeSolid, LiaShippingFastSolid } from "react-icons/lia";

export const TRUST_STRIP_ICONS = {
  truck: FiTruck,
  shield: FiShield,
  refresh: FiRefreshCcw,
  payment: FiCreditCard,
  gift: FiGift,
  handshake: LiaHandshakeSolid,

  headphones: FiHeadphones,
  package: FiPackage,
  lock: FiLock,
  star: FiStar,
  heart: FiHeart,

  check: FiCheckCircle,
  award: FiAward,
  clock: FiClock,
  tag: FiTag,
  thumbs: FiThumbsUp,
  globe: FiGlobe,

  cart: FiShoppingCart,
  location: FiMapPin,
  bell: FiBell,
  message: FiMessageCircle,
  mail: FiMail,
  phone: FiPhone,

  users: FiUsers,
  bookmark: FiBookmark,
  box: FiBox,
  briefcase: FiBriefcase,
  camera: FiCamera,
  coffee: FiCoffee,

  compass: FiCompass,
  feather: FiFeather,
  flag: FiFlag,
  home: FiHome,
  image: FiImage,
  layers: FiLayers,

  support: FiLifeBuoy,
  monitor: FiMonitor,
  moon: FiMoon,
  navigation: FiNavigation,
  paperclip: FiPaperclip,
  send: FiSend,

  settings: FiSettings,
  bag: FiShoppingBag,
  sun: FiSun,
  target: FiTarget,
  tools: FiTool,
  unlock: FiUnlock,

  verifiedUser: FiUserCheck,
  wifi: FiWifi,
  lightning: FiZap,
  shipping: LiaShippingFastSolid,
};
